# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will
brief-intro: Will's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://willalpha.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #None
facebook_username: #None
github_username:  WillAlpha
email: will_private@163.com
weibo_username: #None
zhihu_username: #None
linkedIn_username: #None
dribbble_username: #None

description_footer: Trace My Like!

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: willalpha
disqus_shortname: #willalpha

# statistic analysis
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 84e83bb4e0901f0187b825fc17216225
google_analytics_id: UA-79679922-1 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
